name = "cf-ai-gateway"
compatibility_date = "2026-03-19"
main = "src/index.ts"

[[kv_namespaces]]
binding = "API_KEYS"
id = "e4b54c7c3a184a2cb1483303b7948aff"

[ai]
binding = "AI"

[build]
command = "npm run build"

[observability]
enabled = true
logs = { enabled = true, persist = true, invocation_logs = true }
